// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_ExamMaster_RowScoreLookup
{
    public int RowID { get; set; }

    public int? ChapterID { get; set; }

    public string Semester { get; set; }

    public string Session { get; set; }

    public string ExamType { get; set; }

    public string Category { get; set; }

    public int RawScore { get; set; }

    public int ReportedScore { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }
}