// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblNewsltr
{
    public int colLtrID { get; set; }

    public string colEmail { get; set; }

    public DateTime? RequestedDate { get; set; }

    public DateTime? InsertDate { get; set; }

    public DateTime? ModifiedDate { get; set; }
}