// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_ClassSchedule
{
    public string Semester { get; set; }

    public string Session { get; set; }

    public DateTime ClassDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ChangeBy { get; set; }

    public DateTime? ChangeDate { get; set; }

    public bool? Active { get; set; }

    public int RowID { get; set; }

    public int? ChapterID { get; set; }
}