// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_InstructorMaster
{
    public int InstructorID { get; set; }

    public string Type { get; set; }

    public string Class { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ChangeBy { get; set; }

    public DateTime? ChangeDate { get; set; }

    public string ContactPhone { get; set; }

    public string Section { get; set; }

    public int? ChapterID { get; set; }
}