// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblReportCard
{
    public int mReportCardID { get; set; }

    public int mStudentID { get; set; }

    public string mType { get; set; }

    public int mTotalPoints { get; set; }

    public double mReceivedPoints { get; set; }

    public string mGroup { get; set; }

    public DateTime? mExamDate { get; set; }

    public string mComments { get; set; }

    public DateTime? InsertDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string mSemster { get; set; }

    public string mClass { get; set; }

    public string mSection { get; set; }

    public int? ChapterID { get; set; }
}