// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblTestimonial
{
    public int colTestID { get; set; }

    public string colTestUser { get; set; }

    public string colTestEmail { get; set; }

    public string colTestMessage { get; set; }

    public DateOnly? colTestDate { get; set; }

    public DateTime? InsertDate { get; set; }

    public DateTime? ModifiedDate { get; set; }
}