// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblDonor
{
    public int DonorID { get; set; }

    public string DonorName { get; set; }

    public string DonorLevel { get; set; }

    public int Year { get; set; }

    public string PostedBy { get; set; }

    public DateTime? PostedDate { get; set; }

    public string Semester { get; set; }
}