// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblLookupSemester
{
    public int ID { get; set; }

    public string semester { get; set; }

    public bool? Active { get; set; }

    public DateTime? InsertDate { get; set; }

    public DateOnly? StartingDate { get; set; }

    public string RegistrationStatus { get; set; }

    public DateTime? RegStartDate { get; set; }

    public DateTime? RegCloseDate { get; set; }

    public int? DisplayDocumentsFrom { get; set; }

    public string LastSemester { get; set; }

    public int? JBTotalSpace { get; set; }

    public int? JITotalSpace { get; set; }

    public int? JATotalSpace { get; set; }

    public int? SBTotalSpace { get; set; }

    public int? SITotalSpace { get; set; }

    public int? SATotalSpace { get; set; }

    public int? ChapterID { get; set; }

    public DateOnly? CurrentExamDate { get; set; }

    public DateTime? CurrentExamDueTime { get; set; }

    public string SemesterName { get; set; }

    public string NextSemester { get; set; }

    public int? AITotalSpace { get; set; }

    public int? ATTotalSpace { get; set; }

    public int? STTotalSpace { get; set; }

    public int? DSTotalSpace { get; set; }

    public int? MKTotalSpace { get; set; }

    public int? AMC8TotalSpace { get; set; }

    public int? AMC10TotalSpace { get; set; }

    public int? AMC12TotalSpace { get; set; }
}