// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblStudent
{
    public int colStudentID { get; set; }

    public string colStudentFName { get; set; }

    public string colStudentLName { get; set; }

    public string colStudentEmail { get; set; }

    public string colStudentSchool { get; set; }

    public string colStudentGrade { get; set; }

    public string colStudentstatus { get; set; }

    public string colStudentPicPerm { get; set; }

    public int? colParentID { get; set; }

    public string colStudentEnrolledSession { get; set; }

    public string LiabilitySignature { get; set; }

    public string RuleSignature { get; set; }

    public DateTime? RegisteredDate { get; set; }

    public DateTime? InsertDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ColEventLocation { get; set; }

    public string colStatus { get; set; }

    public string WaitingListStatus { get; set; }

    public int? RegistrationPriority { get; set; }

    public string RequestedLocation { get; set; }

    public int? ChapterID { get; set; }

    public DateTime? SignatureDate { get; set; }

    public virtual AMC_tblUser colParent { get; set; }
}