// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblUserTracking
{
    public int RowID { get; set; }

    public int UserID { get; set; }

    public string UserName { get; set; }

    public string UserType { get; set; }

    public DateTime? LoginDate { get; set; }

    public string IPAddress { get; set; }
}