// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblState
{
    public int colStateID { get; set; }

    public string colAbbriviation { get; set; }

    public string colStateName { get; set; }
}