// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblRegistration
{
    public int ID { get; set; }

    public string Semester { get; set; }

    public int? StudentID { get; set; }

    public DateTime? InsertDate { get; set; }

    public string Status { get; set; }
}