// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblStudentDocument
{
    public int mDocID { get; set; }

    public int mStudentID { get; set; }

    public string mDocName { get; set; }

    public string Description { get; set; }

    public string Type { get; set; }

    public DateTime? InsertDate { get; set; }
}