// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblPostMessage
{
    public int MessageID { get; set; }

    public string Type { get; set; }

    public string Message { get; set; }

    public string PostedBy { get; set; }

    public DateTime? PostedDate { get; set; }

    public bool SendEmail { get; set; }

    public bool Active { get; set; }

    public int? ChapterID { get; set; }
}