// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblVideo
{
    public int mvideoID { get; set; }

    public string mBatch { get; set; }

    public string mTopics { get; set; }

    public string mDescription { get; set; }

    public string mURLName { get; set; }

    public string mSession { get; set; }

    public bool Active { get; set; }

    public DateTime? InsertDate { get; set; }

    public int? mDocID { get; set; }

    public string mSemester { get; set; }
}