// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblUser
{
    public int coluserID { get; set; }

    public string coluserfName { get; set; }

    public string coluserlName { get; set; }

    public string coluserAddress { get; set; }

    public string coluserCity { get; set; }

    public string coluserState { get; set; }

    public string coluserZip { get; set; }

    public string coluserPhNo { get; set; }

    public string coluserEmail { get; set; }

    public string coluserStatus { get; set; }

    public string colSecurelvl { get; set; }

    public DateTime? RegisteredDate { get; set; }

    public DateTime? InsertDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string coluserCountry { get; set; }

    public string colParentEmail { get; set; }

    public virtual ICollection<AMC_tblStudent> AMC_tblStudents { get; set; } = new List<AMC_tblStudent>();
}