// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblAccountReceivable
{
    public int ArID { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string PaymentMode { get; set; }

    public DateTime PaymentDate { get; set; }

    public decimal Amount { get; set; }

    public string PayerType { get; set; }

    public string Documents { get; set; }

    public string Comments { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ChangeBy { get; set; }

    public DateTime? ChangeDate { get; set; }
}