// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblTriangularRegistration
{
    public int RowiID { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Country { get; set; }

    public DateTime? InsertDate { get; set; }
}