// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_ChapterMaster
{
    public int ChapterID { get; set; }

    public string Name { get; set; }

    public string Program { get; set; }

    public string Location { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public string ContactPerson { get; set; }

    public string ContactPhone { get; set; }

    public string ContactEmail { get; set; }

    public string SupportEmail { get; set; }

    public string Emailsuffix { get; set; }

    public DateTime StartingDate { get; set; }

    public bool? Active { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool? IsOnlineExamActive { get; set; }
}