// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblMeetingSchedule
{
    public int RowID { get; set; }

    public int? ChapterID { get; set; }

    public string Class { get; set; }

    public string Section { get; set; }

    public string MeetingProviderURL { get; set; }

    public string MeetingURL { get; set; }

    public string MeetingID { get; set; }

    public string Passcode { get; set; }

    public string AdminLogin { get; set; }

    public string AdminPassCode { get; set; }

    public bool IncludeSection { get; set; }

    public bool Active { get; set; }

    public DateTime? InsertDate { get; set; }

    public DateTime? UpdatedtDate { get; set; }

    public TimeOnly? MeetingTime { get; set; }

    public DateOnly? MeetingDate { get; set; }
}