// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblEmailTracking
{
    public int ID { get; set; }

    public string SendFrom { get; set; }

    public string SendTo { get; set; }

    public string Subject { get; set; }

    public string Message { get; set; }

    public string SendBy { get; set; }

    public DateTime? SendDate { get; set; }

    public string Status { get; set; }

    public int? chapterID { get; set; }

    public string UserType { get; set; }
}