// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_ExamMasterAnswerKey_Bak
{
    public int StudentID { get; set; }

    public string Semester { get; set; }

    public string Class { get; set; }

    public int Question { get; set; }

    public string AnswerKey { get; set; }

    public int Points { get; set; }

    public DateTime CreatedDate { get; set; }

    public string ExamType { get; set; }

    public string Session { get; set; }
}