// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_ClassType
{
    public int RowID { get; set; }

    public string Class { get; set; }

    public string ClassName { get; set; }

    public string Section { get; set; }

    public string StudentEmailGroup { get; set; }

    public string InstructorEmailGroup { get; set; }

    public int DisplayOrder { get; set; }

    public int? ChapterID { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }
}