// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_Country
{
    public int CountryID { get; set; }

    public string CountryCode { get; set; }

    public string CountryName { get; set; }

    public int? DisplayOrder { get; set; }
}