// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_tblChannel
{
    public int ChannelID { get; set; }

    public string Image { get; set; }

    public string Title { get; set; }

    public string Link { get; set; }

    public string Description { get; set; }

    public string Createdby { get; set; }

    public DateTime? CreatedDate { get; set; }
}