// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class AMC_ExamMaster
{
    public string Semester { get; set; }

    public string Class { get; set; }

    public string ExamType { get; set; }

    public int Question { get; set; }

    public string AnswerKey { get; set; }

    public int Points { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int RowID { get; set; }

    public string AnswerType { get; set; }

    public string Category { get; set; }

    public string AnswerDescription { get; set; }

    public string mSession { get; set; }
}