// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class Comment
{
    public int pCommentID { get; set; }

    public string Name { get; set; }

    public string EmailID { get; set; }

    public string Comments { get; set; }

    public DateTime PostedDate { get; set; }

    public DateTime? DeleteDate { get; set; }

    public string DeleteBy { get; set; }
}