// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace pStudyWare20.Data.Models;

public partial class MemberMaster
{
    [Key]
    public int pMemberID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string EmailID { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public DateTime? LastActiveDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ChangeBy { get; set; }

    public DateTime? ChangeDate { get; set; }

    public bool? Approved { get; set; }

    public string MemberType { get; set; }

    public int? CreditScore { get; set; }

    public int? ChapterID { get; set; }

    public string systemAdmin { get; set; }

    public int? DefaultChapter { get; set; }

    public bool? Active { get; set; }

    public string ClassAccess { get; set; }

    public string SuperUser { get; set; }
}