// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class MemberType
{
    public int pMemberTypeID { get; set; }

    public string MemberTypeCd { get; set; }

    public string MemberTypeDesc { get; set; }
}