// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class MemberReference
{
    public int? fMemberAdminID { get; set; }

    public int? fMemberID { get; set; }
}