// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class notificationtemplate
{
    public Guid id { get; set; }

    public string recipient { get; set; }

    public string mode { get; set; }

    public DateTime? created_at { get; set; }
}