// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class pushhoken
{
    public Guid id { get; set; }

    public Guid user_id { get; set; }

    public string token { get; set; }

    public string device_info { get; set; }

    public DateTime? created_at { get; set; }

    public virtual user user { get; set; }
}