// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class StudentLog
{
    public int pStudentLogId { get; set; }

    public int? fMemberId { get; set; }

    public string Subject { get; set; }

    public DateTime? EntryDate { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string Chapter { get; set; }

    public string Summary { get; set; }

    public int? Credit { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ModfiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }
}