// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class SubjectMaster
{
    public int SubjectID { get; set; }

    public string Subject { get; set; }
}