// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class temp
{
    public double? Stdent_Id { get; set; }

    public string type { get; set; }

    public double? Total_Points { get; set; }

    public double? Score { get; set; }

    public string Group { get; set; }

    public DateTime? Exam_date_ { get; set; }

    public double? comment { get; set; }
}