// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pStudyWare20.Data.Models;

public partial class user
{
    public Guid id { get; set; }

    public string name { get; set; }

    public string email { get; set; }

    public string role { get; set; }

    public DateTime? created_at { get; set; }

    public virtual ICollection<coursemembership> coursememberships { get; set; } = new List<coursemembership>();

    public virtual ICollection<pushhoken> pushhokens { get; set; } = new List<pushhoken>();
}