CREATE TABLE [dbo].[AMC_tblStates](
	[colStateID] [int] IDENTITY(1,1) NOT NULL,
	[colAbbriviation] [char](2) NULL,
	[colStateName] [varchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[colStateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]