// This file is used by Code Analysis to suppress warnings
// that are generated by the build process.
// See https://docs.microsoft.com/visualstudio/code-quality/using-suppressions

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Auto-generated EF Core models")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1708:Identifiers should differ by more than case", Justification = "Auto-generated EF Core models")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CS8981:Lower-case type names should not be used", Justification = "Auto-generated EF Core models")]
